In [1]:
import pandas as pd
teste = pd.read_json("./data.json")
teste.info()

<class 'pandas.core.frame.DataFrame'>
Index: 122557 entries, 0 to 122556
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   proposicao            122557 non-null  object
 1   autor                 116929 non-null  object
 2   political_party       102888 non-null  object
 3   relator               5628 non-null    object
 4   proposicao_principal  5523 non-null    object
dtypes: object(5)
memory usage: 5.6+ MB

In [2]:
import pandas as pd
import json

teste = pd.read_json("./data.json")
teste["autor"] = teste["autor"].fillna("placeholder")
teste["autor"] = teste.apply(lambda row: row["relator"] if row["autor"] == "placeholder" else row["autor"], axis=1)
json_object = json.loads('{"ementa": "vazio"}')
# Replace null values in the "proposicao_principal" column with a placeholder value
teste["proposicao_principal"] = teste["proposicao_principal"].fillna("placeholder")
teste["proposicao_principal"] = teste["proposicao_principal"].apply(lambda x: json_object if x == "placeholder" else x)

teste = teste.drop(columns=["relator"])
teste["proposicao"] = teste["proposicao"].drop_duplicates()

In [3]:
teste = teste.dropna()

In [23]:
teste["political_party"]

0        {'nome': 'Partido da República', 'sigla': 'PR'...
1        {'nome': 'Partido da República', 'sigla': 'PR'...
2        {'nome': 'Partido Socialismo e Liberdade', 'si...
3        {'nome': 'Partido Socialismo e Liberdade', 'si...
4        {'nome': 'Partido Socialismo e Liberdade', 'si...
                               ...
69416    {'nome': 'Partido Social Democrático', 'sigla'...
69417    {'nome': 'Republicanos', 'sigla': 'REPUBLICANO...
69418    {'nome': 'Republicanos', 'sigla': 'REPUBLICANO...
69419    {'nome': 'Republicanos', 'sigla': 'REPUBLICANO...
69420    {'nome': 'Republicanos', 'sigla': 'REPUBLICANO...
Name: political_party, Length: 12538, dtype: object

In [33]:
proposicao = pd.json_normalize(teste["proposicao"], max_level=1)
autor = pd.json_normalize(teste["autor"], max_level=1)
proposicao_principal = pd.json_normalize(teste["proposicao_principal"], max_level=1)
political_party = pd.json_normalize(teste["political_party"], max_level=1)
political_party = political_party.rename(columns={"nome": 'nome_partido', 'sigla': "sigla_partido", 'status': 'status_partido', 'total_membros': 'total_membros_partido'})

In [34]:
dataset = pd.concat([ proposicao, autor, proposicao_principal, political_party], axis=1)

In [36]:
dataset

,ementa,ementaDetalhada,ano,keywords,uris.uriAutores,uris.uriPropPrincipal,uris.uriUltimoRelator,nome,cpf,foto,...,escolaridade,uris.uriPartido,ementa,situacao,tipo,keywords,nome_partido,sigla_partido,status_partido,total_membros_partido
0,Dispõe sobre a obrigatoriedade de fotografia n...,Altera a Lei nº 7.444 de 20 de dezembro de 1985.,2003,"Alteração, Lei do Processamento Eletrônico do ...",https://dadosabertos.camara.leg.br/api/v2/prop...,None,None,CARLOS FREDERICO THEODORO NADER,85176427753,https://www.camara.leg.br/internet/deputado/ba...,...,Superior,https://dadosabertos.camara.leg.br/api/v2/part...,vazio,NaN,NaN,NaN,Partido da República,PR,Inativo,0
1,Garante ao acertador de qualquer tipo de jogo ...,,2003,"Garantia, omissão, identificação, ganhador, lo...",https://dadosabertos.camara.leg.br/api/v2/prop...,https://dadosabertos.camara.leg.br/api/v2/prop...,https://dadosabertos.camara.leg.br/api/v2/depu...,ANDRES NAVARRO SANCHEZ,07078570820,https://www.camara.leg.br/internet/deputado/ba...,...,Ensino Fundamental,https://dadosabertos.camara.leg.br/api/v2/part...,"Acrescenta art. 10-B à Lei n° 9.613, de 3 de m...",Aguardando Parecer,Projeto de Lei,"Alteração, Lei de Lavagem de Dinheiro, obrigat...",Partido da República,PR,Inativo,0
2,Dispõe sobre a obrigatoriedade das prestadoras...,,2003,"Obrigatoriedade, concessionária, telefone celu...",https://dadosabertos.camara.leg.br/api/v2/prop...,https://dadosabertos.camara.leg.br/api/v2/prop...,None,FRANCISCO RODRIGUES DE ALENCAR FILHO,26451379700,https://www.camara.leg.br/internet/deputado/ba...,...,Mestrado,https://dadosabertos.camara.leg.br/api/v2/part...,"Altera o inciso IV do art. 3º da Lei nº 9.472,...",Aguardando Parecer,Projeto de Lei,"Alteração, Lei Geral das Telecomunicações, dis...",Partido Socialismo e Liberdade,PSOL,Ativo,13
3,Institui o dia 02 de julho como data histórica...,,2003,"Criação, Dia Nacional da Independência do Bras...",https://dadosabertos.camara.leg.br/api/v2/prop...,None,https://dadosabertos.camara.leg.br/api/v2/depu...,DOUGLAS DE PAULO VIEGAS,25519061807,https://www.camara.leg.br/internet/deputado/ba...,...,None,https://dadosabertos.camara.leg.br/api/v2/part...,vazio,NaN,NaN,NaN,Partido Socialismo e Liberdade,PSOL,Ativo,13
4,Regulamenta o § 7º do art. 37 da Constituição ...,Fixa um período de impedimento ou quarentena d...,2003,"Regulamentação, Constituição Federal, requisit...",https://dadosabertos.camara.leg.br/api/v2/prop...,None,https://dadosabertos.camara.leg.br/api/v2/depu...,GILSON MARQUES VIEIRA,00824207939,https://www.camara.leg.br/internet/deputado/ba...,...,Pós-Graduação,https://dadosabertos.camara.leg.br/api/v2/part...,vazio,NaN,NaN,NaN,Partido Socialismo e Liberdade,PSOL,Ativo,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12533,"Altera a Lei nº 8.069, de 13 de julho de 1990 ...",None,0,None,https://dadosabertos.camara.leg.br/api/v2/prop...,None,None,MARIA LAURA MONTEZA DE SOUZA CARNEIRO,79401546720,https://www.camara.leg.br/internet/deputado/ba...,...,Superior,https://dadosabertos.camara.leg.br/api/v2/part...,vazio,NaN,NaN,NaN,Partido Social Democrático,PSD,Ativo,44
12534,Parecer exarado no RIC n. 296/2024,None,0,None,https://dadosabertos.camara.leg.br/api/v2/prop...,None,None,MARCOS ANTONIO PEREIRA,00963578782,https://www.camara.leg.br/internet/deputado/ba...,...,Pós-Graduação,https://dadosabertos.camara.leg.br/api/v2/part...,vazio,NaN,NaN,NaN,Republicanos,REPUBLICANOS,Ativo,42
12535,Parecer exarado no RIC n. 274/2024,None,0,None,https://dadosabertos.camara.leg.br/api/v2/prop...,None,None,MARCOS ANTONIO PEREIRA,00963578782,https://www.camara.leg.br/internet/deputado/ba...,...,Pós-Graduação,https://dadosabertos.camara.leg.br/api/v2/part...,vazio,NaN,NaN,NaN,Republicanos,REPUBLICANOS,Ativo,42
12536,Parecer exarado no RIC n. 284/2024,None,0,None,https://dadosabertos.camara.leg.br/api/v2/prop...,None,None,MARCOS ANTONIO PEREIRA,00963578782,https://www.camara.leg.br/internet/deputado/ba...,...,Pós-Graduação,https://dadosabertos.camara.leg.br/api/v2/part...,vazio,NaN,NaN,NaN,Republicanos,REPUBLICANOS,Ativo,42
12537,Parecer exarado no RIC n. 290/2024,None,0,None,https://dadosabertos.camara.leg.br/api/v2/prop...,None,None,MARCOS ANTONIO PEREIRA,00963578782,https://www.camara.leg.br/internet/deputado/ba...,...,Pós-Graduação,https://dadosabertos.camara.leg.br/api/v2/part...,vazio,NaN,NaN,NaN,Republicanos,REPUBLICANOS,Ativo,42

In [37]:
dataset["nome"]

0              CARLOS FREDERICO THEODORO NADER
1                       ANDRES NAVARRO SANCHEZ
2         FRANCISCO RODRIGUES DE ALENCAR FILHO
3                      DOUGLAS DE PAULO VIEGAS
4                        GILSON MARQUES VIEIRA
                         ...
12533    MARIA LAURA MONTEZA DE SOUZA CARNEIRO
12534                   MARCOS ANTONIO PEREIRA
12535                   MARCOS ANTONIO PEREIRA
12536                   MARCOS ANTONIO PEREIRA
12537                   MARCOS ANTONIO PEREIRA
Name: nome, Length: 12538, dtype: object

In [38]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12538 entries, 0 to 12537
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ementa                 12538 non-null  object
 1   ementaDetalhada        6598 non-null   object
 2   ano                    12538 non-null  int64
 3   keywords               6596 non-null   object
 4   uris.uriAutores        12538 non-null  object
 5   uris.uriPropPrincipal  2334 non-null   object
 6   uris.uriUltimoRelator  3688 non-null   object
 7   nome                   12538 non-null  object
 8   cpf                    12538 non-null  object
 9   foto                   12538 non-null  object
 10  sexo                   12538 non-null  object
 11  nascimento             12538 non-null  object
 12  local_nascimento       12538 non-null  object
 13  escolaridade           12228 non-null  object
 14  uris.uriPartido        12538 non-null  object
 15  ementa                 12538 non-null  object
 16  situacao               2150 non-null   object
 17  tipo                   2334 non-null   object
 18  keywords               2311 non-null   object
 19  nome_partido           12538 non-null  object
 20  sigla_partido          12538 non-null  object
 21  status_partido         12519 non-null  object
 22  total_membros_partido  12538 non-null  object
dtypes: int64(1), object(22)
memory usage: 2.2+ MB

In [39]:
dataset["nome"]

0              CARLOS FREDERICO THEODORO NADER
1                       ANDRES NAVARRO SANCHEZ
2         FRANCISCO RODRIGUES DE ALENCAR FILHO
3                      DOUGLAS DE PAULO VIEGAS
4                        GILSON MARQUES VIEIRA
                         ...
12533    MARIA LAURA MONTEZA DE SOUZA CARNEIRO
12534                   MARCOS ANTONIO PEREIRA
12535                   MARCOS ANTONIO PEREIRA
12536                   MARCOS ANTONIO PEREIRA
12537                   MARCOS ANTONIO PEREIRA
Name: nome, Length: 12538, dtype: object

In [40]:
cand1 = pd.read_csv("consulta_cand_2000_BRASIL.csv", encoding="latin-1", delimiter=";")
cand2 = pd.read_csv("consulta_cand_2002_BRASIL.csv", encoding="latin-1", delimiter=";")
cand3 = pd.read_csv("consulta_cand_2004_BRASIL.csv", encoding="latin-1", delimiter=";")
cand4 = pd.read_csv("consulta_cand_2006_BRASIL.csv", encoding="latin-1", delimiter=";")
cand5 = pd.read_csv("consulta_cand_2008_BRASIL.csv", encoding="latin-1", delimiter=";")
cand6 = pd.read_csv("consulta_cand_2010_BRASIL.csv", encoding="latin-1", delimiter=";")
cand7 = pd.read_csv("consulta_cand_2012_BRASIL.csv", encoding="latin-1", delimiter=";")

cand8 = pd.read_csv("consulta_cand_2014_BRASIL.csv", encoding="latin-1", delimiter=";")
cand9 = pd.read_csv("consulta_cand_2016_BRASIL.csv", encoding="latin-1", delimiter=";")
cand10 = pd.read_csv("consulta_cand_2018_BRASIL.csv", encoding="latin-1", delimiter=";")
cand11 = pd.read_csv("consulta_cand_2020_BRASIL.csv", encoding="latin-1", delimiter=";")
cand12 = pd.read_csv("consulta_cand_2022_BRASIL.csv", encoding="latin-1", delimiter=";")

candidatos = pd.concat([cand1, cand2, cand3, cand4, cand5, cand6, cand7, cand8, cand9,cand10,cand11,cand12,])

C:\Users\alexa\AppData\Local\Temp\ipykernel_22612\2924868582.py:1: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  cand1 = pd.read_csv("consulta_cand_2000_BRASIL.csv", encoding="latin-1", delimiter=";")
C:\Users\alexa\AppData\Local\Temp\ipykernel_22612\2924868582.py:3: DtypeWarning: Columns (20,40) have mixed types. Specify dtype option on import or set low_memory=False.
  cand3 = pd.read_csv("consulta_cand_2004_BRASIL.csv", encoding="latin-1", delimiter=";")
C:\Users\alexa\AppData\Local\Temp\ipykernel_22612\2924868582.py:7: DtypeWarning: Columns (57) have mixed types. Specify dtype option on import or set low_memory=False.
  cand7 = pd.read_csv("consulta_cand_2012_BRASIL.csv", encoding="latin-1", delimiter=";")
C:\Users\alexa\AppData\Local\Temp\ipykernel_22612\2924868582.py:9: DtypeWarning: Columns (57) have mixed types. Specify dtype option on import or set low_memory=False.
  cand8 = pd.read_csv("consulta_cand_2014_BRASIL.csv", encoding="latin-1", delimiter=";")
C:\Users\alexa\AppData\Local\Temp\ipykernel_22612\2924868582.py:10: DtypeWarning: Columns (61) have mixed types. Specify dtype option on import or set low_memory=False.
  cand9 = pd.read_csv("consulta_cand_2016_BRASIL.csv", encoding="latin-1", delimiter=";")

In [41]:
candidatos = candidatos.drop_duplicates(subset=["NM_CANDIDATO"]).reset_index(drop=True)
candidatos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1813433 entries, 0 to 1813432
Data columns (total 75 columns):
 #   Column                         Dtype
---  ------                         -----
 0   DT_GERACAO                     object
 1   HH_GERACAO                     object
 2   ANO_ELEICAO                    int64
 3   CD_TIPO_ELEICAO                int64
 4   NM_TIPO_ELEICAO                object
 5   NR_TURNO                       int64
 6   CD_ELEICAO                     int64
 7   DS_ELEICAO                     object
 8   DT_ELEICAO                     object
 9   TP_ABRANGENCIA                 object
 10  SG_UF                          object
 11  SG_UE                          object
 12  NM_UE                          object
 13  CD_CARGO                       int64
 14  DS_CARGO                       object
 15  SQ_CANDIDATO                   int64
 16  NR_CANDIDATO                   int64
 17  NM_CANDIDATO                   object
 18  NM_URNA_CANDIDATO              object
 19  NM_SOCIAL_CANDIDATO            object
 20  NR_CPF_CANDIDATO               object
 21  NM_EMAIL                       object
 22  CD_SITUACAO_CANDIDATURA        int64
 23  DS_SITUACAO_CANDIDATURA        object
 24  CD_DETALHE_SITUACAO_CAND       int64
 25  DS_DETALHE_SITUACAO_CAND       object
 26  TP_AGREMIACAO                  object
 27  NR_PARTIDO                     int64
 28  SG_PARTIDO                     object
 29  NM_PARTIDO                     object
 30  SQ_COLIGACAO                   int64
 31  NM_COLIGACAO                   object
 32  DS_COMPOSICAO_COLIGACAO        object
 33  CD_NACIONALIDADE               int64
 34  DS_NACIONALIDADE               object
 35  SG_UF_NASCIMENTO               object
 36  CD_MUNICIPIO_NASCIMENTO        int64
 37  NM_MUNICIPIO_NASCIMENTO        object
 38  DT_NASCIMENTO                  object
 39  NR_IDADE_DATA_POSSE            float64
 40  NR_TITULO_ELEITORAL_CANDIDATO  object
 41  CD_GENERO                      int64
 42  DS_GENERO                      object
 43  CD_GRAU_INSTRUCAO              int64
 44  DS_GRAU_INSTRUCAO              object
 45  CD_ESTADO_CIVIL                int64
 46  DS_ESTADO_CIVIL                object
 47  CD_COR_RACA                    int64
 48  DS_COR_RACA                    object
 49  CD_OCUPACAO                    int64
 50  DS_OCUPACAO                    object
 51  VR_DESPESA_MAX_CAMPANHA        float64
 52  CD_SIT_TOT_TURNO               int64
 53  DS_SIT_TOT_TURNO               object
 54  ST_REELEICAO                   object
 55  ST_DECLARAR_BENS               object
 56  NR_PROTOCOLO_CANDIDATURA       int64
 57  NR_PROCESSO                    object
 58  CD_SITUACAO_CANDIDATO_PLEITO   int64
 59  DS_SITUACAO_CANDIDATO_PLEITO   object
 60  CD_SITUACAO_CANDIDATO_URNA     int64
 61  DS_SITUACAO_CANDIDATO_URNA     object
 62  ST_CANDIDATO_INSERIDO_URNA     object
 63  NM_TIPO_DESTINACAO_VOTOS       object
 64  CD_SITUACAO_CANDIDATO_TOT      float64
 65  DS_SITUACAO_CANDIDATO_TOT      object
 66  ST_PREST_CONTAS                object
 67  ST_SUBSTITUIDO                 object
 68  SQ_SUBSTITUIDO                 float64
 69  SQ_ORDEM_SUPLENCIA             float64
 70  DT_ACEITE_CANDIDATURA          object
 71  NR_FEDERACAO                   float64
 72  NM_FEDERACAO                   object
 73  SG_FEDERACAO                   object
 74  DS_COMPOSICAO_FEDERACAO        object
dtypes: float64(6), int64(22), object(47)
memory usage: 1.0+ GB

In [42]:
nome = candidatos["NM_CANDIDATO"].reset_index(drop=True)
cor = candidatos["DS_COR_RACA"].reset_index(drop=True)

In [43]:
candidato = pd.DataFrame()
candidato["nome"] = nome
candidato["cor"] = cor

In [44]:
candidato

                                                    nome     cor
0                                 PAULO RUCAS BRITO ACHY     #NE
1                                        EDEMIR DE SOUZA     #NE
2                                   WAGNER LUIS DO PRADO     #NE
3                                VALQUÍRIA DE LEMOS MELO     #NE
4                           ALVARO LUIZ BORTOLOTTO PREIS     #NE
...                                                  ...     ...
1813428                           MANOEL ANTÔNIO DE MELO   PARDA
1813429              SILVIA HELENA FREIRE DE PAIVA SOUZA  BRANCA
1813430                         JOSE SILVA MIGUEL JUNIOR  BRANCA
1813431                          ANGELINA REJANE DO VALE   PARDA
1813432  MARIÂNGELA FERDINANDA PEREIRA MARINHO RODRIGUES   PARDA

[1813433 rows x 2 columns]

In [45]:
dataset2 = pd.merge(dataset, candidato, on="nome")

In [46]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12538 entries, 0 to 12537
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ementa                 12538 non-null  object
 1   ementaDetalhada        6598 non-null   object
 2   ano                    12538 non-null  int64
 3   keywords               6596 non-null   object
 4   uris.uriAutores        12538 non-null  object
 5   uris.uriPropPrincipal  2334 non-null   object
 6   uris.uriUltimoRelator  3688 non-null   object
 7   nome                   12538 non-null  object
 8   cpf                    12538 non-null  object
 9   foto                   12538 non-null  object
 10  sexo                   12538 non-null  object
 11  nascimento             12538 non-null  object
 12  local_nascimento       12538 non-null  object
 13  escolaridade           12228 non-null  object
 14  uris.uriPartido        12538 non-null  object
 15  ementa                 12538 non-null  object
 16  situacao               2150 non-null   object
 17  tipo                   2334 non-null   object
 18  keywords               2311 non-null   object
 19  nome_partido           12538 non-null  object
 20  sigla_partido          12538 non-null  object
 21  status_partido         12519 non-null  object
 22  total_membros_partido  12538 non-null  object
dtypes: int64(1), object(22)
memory usage: 2.2+ MB

In [47]:
dataset2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11737 entries, 0 to 11736
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ementa                 11737 non-null  object
 1   ementaDetalhada        6292 non-null   object
 2   ano                    11737 non-null  int64
 3   keywords               6290 non-null   object
 4   uris.uriAutores        11737 non-null  object
 5   uris.uriPropPrincipal  2242 non-null   object
 6   uris.uriUltimoRelator  3497 non-null   object
 7   nome                   11737 non-null  object
 8   cpf                    11737 non-null  object
 9   foto                   11737 non-null  object
 10  sexo                   11737 non-null  object
 11  nascimento             11737 non-null  object
 12  local_nascimento       11737 non-null  object
 13  escolaridade           11471 non-null  object
 14  uris.uriPartido        11737 non-null  object
 15  ementa                 11737 non-null  object
 16  situacao               2068 non-null   object
 17  tipo                   2242 non-null   object
 18  keywords               2221 non-null   object
 19  nome_partido           11737 non-null  object
 20  sigla_partido          11737 non-null  object
 21  status_partido         11718 non-null  object
 22  total_membros_partido  11737 non-null  object
 23  cor                    11737 non-null  object
dtypes: int64(1), object(23)
memory usage: 2.1+ MB

In [48]:
dataset2.to_csv("./cor_da_justica.csv")