In [2]:
import pandas as pd
teste = pd.read_json("./data.json")
teste.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3100 entries, 0 to 3099
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   proposicao            3100 non-null   object
 1   autor                 1316 non-null   object
 2   relator               1784 non-null   object
 3   proposicao_principal  1338 non-null   object
dtypes: object(4)
memory usage: 121.1+ KB

In [5]:
import pandas as pd
import json

teste = pd.read_json("./data.json")
teste["autor"] = teste["autor"].fillna("placeholder")
teste["autor"] = teste.apply(lambda row: row["relator"] if row["autor"] == "placeholder" else row["autor"], axis=1)
json_object = json.loads('{"ementa": "vazio"}')
# Replace null values in the "proposicao_principal" column with a placeholder value
teste["proposicao_principal"] = teste["proposicao_principal"].fillna("placeholder")
teste["proposicao_principal"] = teste["proposicao_principal"].apply(lambda x: json_object if x == "placeholder" else x)

teste = teste.drop(columns=["relator"])
teste["proposicao"] = teste["proposicao"].drop_duplicates()

In [17]:
teste = teste.dropna()

In [19]:
proposicao = pd.json_normalize(teste["proposicao"], max_level=1)
autor = pd.json_normalize(teste["autor"], max_level=1)
proposicao_principal = pd.json_normalize(teste["proposicao_principal"], max_level=1)

In [20]:
dataset = pd.concat([ proposicao, autor, proposicao_principal], axis=1)

In [21]:
dataset

,ementa,ementaDetalhada,keywords,uris.uriAutores,uris.uriPropPrincipal,uris.uriUltimoRelator,nome,cpf,foto,sexo,nascimento,local_nascimento,escolaridade,orgão,ementa,situacao,tipo,keywords
0,Dispõe sobre a obrigatoriedade de fotografia n...,Altera a Lei nº 7.444 de 20 de dezembro de 1985.,"Alteração, Lei do Processamento Eletrônico do ...",https://dadosabertos.camara.leg.br/api/v2/prop...,None,None,CARLOS FREDERICO THEODORO NADER,85176427753,https://www.camara.leg.br/internet/deputado/ba...,M,1965-09-21,Barra Mansa - RJ,Superior,NaN,vazio,NaN,NaN,NaN
1,Garante ao acertador de qualquer tipo de jogo ...,,"Garantia, omissão, identificação, ganhador, lo...",https://dadosabertos.camara.leg.br/api/v2/prop...,https://dadosabertos.camara.leg.br/api/v2/prop...,https://dadosabertos.camara.leg.br/api/v2/depu...,ANDRES NAVARRO SANCHEZ,07078570820,https://www.camara.leg.br/internet/deputado/ba...,M,1963-12-24,Limeira - SP,Ensino Fundamental,NaN,"Acrescenta art. 10-B à Lei n° 9.613, de 3 de m...",Aguardando Parecer,Projeto de Lei,"Alteração, Lei de Lavagem de Dinheiro, obrigat..."
2,Dispõe sobre a obrigatoriedade das prestadoras...,,"Obrigatoriedade, concessionária, telefone celu...",https://dadosabertos.camara.leg.br/api/v2/prop...,https://dadosabertos.camara.leg.br/api/v2/prop...,None,FRANCISCO RODRIGUES DE ALENCAR FILHO,26451379700,https://www.camara.leg.br/internet/deputado/ba...,M,1949-10-19,Rio de Janeiro - RJ,Mestrado,NaN,"Altera o inciso IV do art. 3º da Lei nº 9.472,...",Aguardando Parecer,Projeto de Lei,"Alteração, Lei Geral das Telecomunicações, dis..."
3,Institui o dia 02 de julho como data histórica...,,"Criação, Dia Nacional da Independência do Bras...",https://dadosabertos.camara.leg.br/api/v2/prop...,None,https://dadosabertos.camara.leg.br/api/v2/depu...,DOUGLAS DE PAULO VIEGAS,25519061807,https://www.camara.leg.br/internet/deputado/ba...,M,1979-06-19,São Paulo - SP,None,NaN,vazio,NaN,NaN,NaN
4,Altera o inciso I do § 1º do art. 68 da Lei nº...,,"Alteração, Nova Lei de Patentes, licenciament...",https://dadosabertos.camara.leg.br/api/v2/prop...,None,https://dadosabertos.camara.leg.br/api/v2/depu...,CÁSSIO MURILO GALDINO DE ARAÚJO,03182571494,https://www.camara.leg.br/internet/deputado/ba...,M,1980-07-02,Pocinhos - PB,Superior,NaN,vazio,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2974,"Altera a Lei nº 4.375, de 1964, dispondo sobre...",,"Alteração, Lei do Serviço Militar, critério, s...",https://dadosabertos.camara.leg.br/api/v2/prop...,None,https://dadosabertos.camara.leg.br/api/v2/depu...,LUCIANO LORENZINI ZUCCO,72434325068,https://www.camara.leg.br/internet/deputado/ba...,M,1974-03-09,Alegrete - RS,Mestrado,NaN,vazio,NaN,NaN,NaN
2975,"Obriga a manutenção, reinscrição ou disponibil...",,"Obrigatoriedade, manutenção, reinclusão, infor...",https://dadosabertos.camara.leg.br/api/v2/prop...,None,https://dadosabertos.camara.leg.br/api/v2/depu...,FLÁVIO RODRIGUES NOGUEIRA,04826604300,https://www.camara.leg.br/internet/deputado/ba...,M,1953-02-27,Alto Santo - CE,Superior,NaN,vazio,NaN,NaN,NaN
2976,"Acrescenta ao Código de Defesa do Consumidor, ...",,"Alteração, Código de Defesa do Consumidor, sus...",https://dadosabertos.camara.leg.br/api/v2/prop...,https://dadosabertos.camara.leg.br/api/v2/prop...,None,PEDRO AUGUSTO GEROMEL BEZERRA DE MENEZES,87850885368,https://www.camara.leg.br/internet/deputado/ba...,M,1980-10-11,Juazeiro do Norte - CE,Pós-Graduação,NaN,Altera o artigo 52 do Código de Defesa do Cons...,Aguardando Parecer,Projeto de Lei,"Alteração, Código de Defesa do Consumidor, con..."
2977,Institui a proibição de que estabelecimentos c...,,"Proibição, estabelecimento comercial, fabrican...",https://dadosabertos.camara.leg.br/api/v2/prop...,https://dadosabertos.camara.leg.br/api/v2/prop...,None,JOSE MARIO SCHREINER,41877004987,https://www.camara.leg.br/internet/deputado/ba...,M,1961-02-08,Porto União - SC,Ensino Técnico,NaN,"Altera a Lei nº 1.283, de 18 de dezembro de 19...",Tramitando em Conjunto,Projeto de Lei,"Alteração, Lei Federal, proibição, utilização,..."
2978,"Altera as Leis números 11.126, de 27 de junho ...",,"Alreração, Lei Federal, Lei Berenice Piana, ga...",https://dadosabertos.camara.leg.br/api/v2/prop...,https://dadosabertos.camara.leg.br/api/v2/prop...,None,ALCIBIO MESQUITA BIBO NUNES,27236056049,https://www.camara.leg.br/internet/deputado/ba...,M,1957-01-09,Cruz Alta - RS,Superior Incompleto,NaN,"Garante o direito de ingresso e permanência, e...",Tramitando em Conjunto,Projeto de Lei,"Alteração, Lei Federal, garantia, pessoa com d..."

In [22]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2979 entries, 0 to 2978
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ementa                 2979 non-null   object
 1   ementaDetalhada        2933 non-null   object
 2   keywords               2933 non-null   object
 3   uris.uriAutores        2979 non-null   object
 4   uris.uriPropPrincipal  1289 non-null   object
 5   uris.uriUltimoRelator  1713 non-null   object
 6   nome                   2979 non-null   object
 7   cpf                    2971 non-null   object
 8   foto                   2959 non-null   object
 9   sexo                   2959 non-null   object
 10  nascimento             2959 non-null   object
 11  local_nascimento       2959 non-null   object
 12  escolaridade           2903 non-null   object
 13  orgão                  12 non-null     object
 14  ementa                 2979 non-null   object
 15  situacao               1168 non-null   object
 16  tipo                   1289 non-null   object
 17  keywords               1289 non-null   object
dtypes: object(18)
memory usage: 419.1+ KB

In [23]:
dataset["nome"]

0                CARLOS FREDERICO THEODORO NADER
1                         ANDRES NAVARRO SANCHEZ
2           FRANCISCO RODRIGUES DE ALENCAR FILHO
3                        DOUGLAS DE PAULO VIEGAS
4                CÁSSIO MURILO GALDINO DE ARAÚJO
                          ...
2974                     LUCIANO LORENZINI ZUCCO
2975                   FLÁVIO RODRIGUES NOGUEIRA
2976    PEDRO AUGUSTO GEROMEL BEZERRA DE MENEZES
2977                        JOSE MARIO SCHREINER
2978                 ALCIBIO MESQUITA BIBO NUNES
Name: nome, Length: 2979, dtype: object

In [24]:
cand1 = pd.read_csv("consulta_cand_2000_BRASIL.csv", encoding="latin-1", delimiter=";")
cand2 = pd.read_csv("consulta_cand_2002_BRASIL.csv", encoding="latin-1", delimiter=";")
cand3 = pd.read_csv("consulta_cand_2004_BRASIL.csv", encoding="latin-1", delimiter=";")
cand4 = pd.read_csv("consulta_cand_2006_BRASIL.csv", encoding="latin-1", delimiter=";")
cand5 = pd.read_csv("consulta_cand_2008_BRASIL.csv", encoding="latin-1", delimiter=";")
cand6 = pd.read_csv("consulta_cand_2010_BRASIL.csv", encoding="latin-1", delimiter=";")
cand7 = pd.read_csv("consulta_cand_2012_BRASIL.csv", encoding="latin-1", delimiter=";")

cand8 = pd.read_csv("consulta_cand_2014_BRASIL.csv", encoding="latin-1", delimiter=";")
cand9 = pd.read_csv("consulta_cand_2016_BRASIL.csv", encoding="latin-1", delimiter=";")
cand10 = pd.read_csv("consulta_cand_2018_BRASIL.csv", encoding="latin-1", delimiter=";")
cand11 = pd.read_csv("consulta_cand_2020_BRASIL.csv", encoding="latin-1", delimiter=";")
cand12 = pd.read_csv("consulta_cand_2022_BRASIL.csv", encoding="latin-1", delimiter=";")

candidatos = pd.concat([cand1, cand2, cand3, cand4, cand5, cand6, cand7, cand8, cand9,cand10,cand11,cand12,])

C:\Users\alexa\AppData\Local\Temp\ipykernel_2240\2924868582.py:1: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  cand1 = pd.read_csv("consulta_cand_2000_BRASIL.csv", encoding="latin-1", delimiter=";")
C:\Users\alexa\AppData\Local\Temp\ipykernel_2240\2924868582.py:3: DtypeWarning: Columns (20,40) have mixed types. Specify dtype option on import or set low_memory=False.
  cand3 = pd.read_csv("consulta_cand_2004_BRASIL.csv", encoding="latin-1", delimiter=";")
C:\Users\alexa\AppData\Local\Temp\ipykernel_2240\2924868582.py:7: DtypeWarning: Columns (57) have mixed types. Specify dtype option on import or set low_memory=False.
  cand7 = pd.read_csv("consulta_cand_2012_BRASIL.csv", encoding="latin-1", delimiter=";")
C:\Users\alexa\AppData\Local\Temp\ipykernel_2240\2924868582.py:9: DtypeWarning: Columns (57) have mixed types. Specify dtype option on import or set low_memory=False.
  cand8 = pd.read_csv("consulta_cand_2014_BRASIL.csv", encoding="latin-1", delimiter=";")
C:\Users\alexa\AppData\Local\Temp\ipykernel_2240\2924868582.py:10: DtypeWarning: Columns (61) have mixed types. Specify dtype option on import or set low_memory=False.
  cand9 = pd.read_csv("consulta_cand_2016_BRASIL.csv", encoding="latin-1", delimiter=";")

In [25]:
candidatos = candidatos.drop_duplicates(subset=["NM_CANDIDATO"]).reset_index(drop=True)
candidatos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1813433 entries, 0 to 1813432
Data columns (total 75 columns):
 #   Column                         Dtype
---  ------                         -----
 0   DT_GERACAO                     object
 1   HH_GERACAO                     object
 2   ANO_ELEICAO                    int64
 3   CD_TIPO_ELEICAO                int64
 4   NM_TIPO_ELEICAO                object
 5   NR_TURNO                       int64
 6   CD_ELEICAO                     int64
 7   DS_ELEICAO                     object
 8   DT_ELEICAO                     object
 9   TP_ABRANGENCIA                 object
 10  SG_UF                          object
 11  SG_UE                          object
 12  NM_UE                          object
 13  CD_CARGO                       int64
 14  DS_CARGO                       object
 15  SQ_CANDIDATO                   int64
 16  NR_CANDIDATO                   int64
 17  NM_CANDIDATO                   object
 18  NM_URNA_CANDIDATO              object
 19  NM_SOCIAL_CANDIDATO            object
 20  NR_CPF_CANDIDATO               object
 21  NM_EMAIL                       object
 22  CD_SITUACAO_CANDIDATURA        int64
 23  DS_SITUACAO_CANDIDATURA        object
 24  CD_DETALHE_SITUACAO_CAND       int64
 25  DS_DETALHE_SITUACAO_CAND       object
 26  TP_AGREMIACAO                  object
 27  NR_PARTIDO                     int64
 28  SG_PARTIDO                     object
 29  NM_PARTIDO                     object
 30  SQ_COLIGACAO                   int64
 31  NM_COLIGACAO                   object
 32  DS_COMPOSICAO_COLIGACAO        object
 33  CD_NACIONALIDADE               int64
 34  DS_NACIONALIDADE               object
 35  SG_UF_NASCIMENTO               object
 36  CD_MUNICIPIO_NASCIMENTO        int64
 37  NM_MUNICIPIO_NASCIMENTO        object
 38  DT_NASCIMENTO                  object
 39  NR_IDADE_DATA_POSSE            float64
 40  NR_TITULO_ELEITORAL_CANDIDATO  object
 41  CD_GENERO                      int64
 42  DS_GENERO                      object
 43  CD_GRAU_INSTRUCAO              int64
 44  DS_GRAU_INSTRUCAO              object
 45  CD_ESTADO_CIVIL                int64
 46  DS_ESTADO_CIVIL                object
 47  CD_COR_RACA                    int64
 48  DS_COR_RACA                    object
 49  CD_OCUPACAO                    int64
 50  DS_OCUPACAO                    object
 51  VR_DESPESA_MAX_CAMPANHA        float64
 52  CD_SIT_TOT_TURNO               int64
 53  DS_SIT_TOT_TURNO               object
 54  ST_REELEICAO                   object
 55  ST_DECLARAR_BENS               object
 56  NR_PROTOCOLO_CANDIDATURA       int64
 57  NR_PROCESSO                    object
 58  CD_SITUACAO_CANDIDATO_PLEITO   int64
 59  DS_SITUACAO_CANDIDATO_PLEITO   object
 60  CD_SITUACAO_CANDIDATO_URNA     int64
 61  DS_SITUACAO_CANDIDATO_URNA     object
 62  ST_CANDIDATO_INSERIDO_URNA     object
 63  NM_TIPO_DESTINACAO_VOTOS       object
 64  CD_SITUACAO_CANDIDATO_TOT      float64
 65  DS_SITUACAO_CANDIDATO_TOT      object
 66  ST_PREST_CONTAS                object
 67  ST_SUBSTITUIDO                 object
 68  SQ_SUBSTITUIDO                 float64
 69  SQ_ORDEM_SUPLENCIA             float64
 70  DT_ACEITE_CANDIDATURA          object
 71  NR_FEDERACAO                   float64
 72  NM_FEDERACAO                   object
 73  SG_FEDERACAO                   object
 74  DS_COMPOSICAO_FEDERACAO        object
dtypes: float64(6), int64(22), object(47)
memory usage: 1.0+ GB

In [26]:
nome = candidatos["NM_CANDIDATO"].reset_index(drop=True)
cor = candidatos["DS_COR_RACA"].reset_index(drop=True)

In [27]:
candidato = pd.DataFrame()
candidato["nome"] = nome
candidato["cor"] = cor

In [28]:
candidato

                                                    nome     cor
0                                 PAULO RUCAS BRITO ACHY     #NE
1                                        EDEMIR DE SOUZA     #NE
2                                   WAGNER LUIS DO PRADO     #NE
3                                VALQUÍRIA DE LEMOS MELO     #NE
4                           ALVARO LUIZ BORTOLOTTO PREIS     #NE
...                                                  ...     ...
1813428                           MANOEL ANTÔNIO DE MELO   PARDA
1813429              SILVIA HELENA FREIRE DE PAIVA SOUZA  BRANCA
1813430                         JOSE SILVA MIGUEL JUNIOR  BRANCA
1813431                          ANGELINA REJANE DO VALE   PARDA
1813432  MARIÂNGELA FERDINANDA PEREIRA MARINHO RODRIGUES   PARDA

[1813433 rows x 2 columns]

In [29]:
dataset2 = pd.merge(dataset, candidato, on="nome")

In [30]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2979 entries, 0 to 2978
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ementa                 2979 non-null   object
 1   ementaDetalhada        2933 non-null   object
 2   keywords               2933 non-null   object
 3   uris.uriAutores        2979 non-null   object
 4   uris.uriPropPrincipal  1289 non-null   object
 5   uris.uriUltimoRelator  1713 non-null   object
 6   nome                   2979 non-null   object
 7   cpf                    2971 non-null   object
 8   foto                   2959 non-null   object
 9   sexo                   2959 non-null   object
 10  nascimento             2959 non-null   object
 11  local_nascimento       2959 non-null   object
 12  escolaridade           2903 non-null   object
 13  orgão                  12 non-null     object
 14  ementa                 2979 non-null   object
 15  situacao               1168 non-null   object
 16  tipo                   1289 non-null   object
 17  keywords               1289 non-null   object
dtypes: object(18)
memory usage: 419.1+ KB

In [31]:
dataset2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2798 entries, 0 to 2797
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ementa                 2798 non-null   object
 1   ementaDetalhada        2752 non-null   object
 2   keywords               2752 non-null   object
 3   uris.uriAutores        2798 non-null   object
 4   uris.uriPropPrincipal  1220 non-null   object
 5   uris.uriUltimoRelator  1598 non-null   object
 6   nome                   2798 non-null   object
 7   cpf                    2798 non-null   object
 8   foto                   2798 non-null   object
 9   sexo                   2798 non-null   object
 10  nascimento             2798 non-null   object
 11  local_nascimento       2798 non-null   object
 12  escolaridade           2750 non-null   object
 13  orgão                  0 non-null      object
 14  ementa                 2798 non-null   object
 15  situacao               1106 non-null   object
 16  tipo                   1220 non-null   object
 17  keywords               1220 non-null   object
 18  cor                    2798 non-null   object
dtypes: object(19)
memory usage: 415.5+ KB

In [32]:
dataset2.to_csv("./cor_da_justica.csv")